[package]
name = "parrot_hat_follow"
version = "0.1.0"
authors = ["VaranTavers <tasnadi98@freemail.hu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust_drone_follow = "^0.3.0"
parrot_ar_drone = "^0.1.1"
